// <auto-generated />
using System;
using CSVtoDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSVtoDb.Migrations
{
    [DbContext(typeof(BookingsDbContext))]
    [Migration("20221208134939_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CSVtoDb.Models.BookingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adults")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDateAndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("Children")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtrasBookedOnline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestPhone1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestPhone2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nights")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OTAReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherRevenue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaidAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromoCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PromoDiscount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RatePlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomUnitName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoomUnitRevenue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomUnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
